name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1, 3.2, 3.3]
        rails: [61, 70, 71, 72]

        # Rails 7.2 requires ruby 3.1 and higher
        include:
          - ruby: "3.0"
            rails: 61
          - ruby: "3.0"
            rails: 70
          - ruby: "3.0"
            rails: 71
    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: run tests
        run: bundle exec rake
